In [1]:
import pandas as pd
pd.set_option('display.max_colwidth',100)
import nltk

In [2]:
t_data=pd.read_csv('/content/drive/MyDrive/Ankit/EACL 2021 dec 2020/Hope speech/malyalam/malayalam_hope_train.csv',names=["text","label","NaN"], sep='\t')
t_data.pop('NaN')
t_data

text            label
0                                      @arya s nair may be athile karthikayude charctr bisexual ayirikkum  Non_hope_speech
1             വാങ്ങിയത് എന്ത് കുന്തം ആയാലും കളയാൻ പറ്റില്ലല്ലോ ഇനി വാങ്ങാതിരിക്കാൻ ശ്രദ്ധിക്കുക Jai India  Non_hope_speech
2     മാറുമറയ്ക്കാൻ നടത്തിയ സമരം ഒരു previlege issue  ആയിരുന്നു...അത് ഈ വിഷയവുമായി കമ്പയർ ചെയ്യാൻ പറ്റ...      Hope_speech
3             ഇഷാനെ കൂടുതല് കെട്ടിപിടിക്കേണ്ട ഞങ്ങൾക്കറിയാം ഇഷാന്  സൂര്യയോട് ഇച്ചിരി കൊഞ്ചൽ കൂടുതലാണെന്ന്  Non_hope_speech
4     ഇന്ത്യ ഇസ്‌ലാമിക രാജ്യമല്ല.. ഇന്ത്യൻ ഭരണഘടന മാത്രമേ ഇന്ത്യൻ പൗരന്മാർ നോക്കേണ്ടതുളൂ.  ഇന്ത്യൻ നിയ...      Hope_speech
...                                                                                                   ...              ...
8559                                                              Evan eatha eee pottan oru vivaravumilla  Non_hope_speech
8560                                               Ithinu pakaramayi upayogikkan pattunna Indian app undo  Non_hope_speech
8561                                                                                 സാറിന് നല്ലത് വരട്ടെ  Non_hope_speech
8562                            ഇങ്ങനത്തെ നല്ല നല്ല അറിവുകൾ പറഞ്ഞു തരുന്ന ഈ ഡോക്ടർക് ഇരിക്കട്ടെ ഒരു നന്ദി      Hope_speech
8563  Happy wedding Anniverserygod bless you. കരയെല്ലേ അമ്മേ. സന്തോഷത്തോടെ  ഇഷാനിക്കയോടും മൂന്ന് അമ്മമ...      Hope_speech

[8564 rows x 2 columns]

In [ ]:
t_data['text']=t_data['text'].str.lower()       #changing into lower case       (remove and check acc too)

In [ ]:
t_data['text']=t_data['text'].str.strip()       #remove white spaces
t_data['text']=t_data['text'].str.replace(r'\d+','')   #remove numbers
t_data['text']=t_data['text'].str.replace('[^\w\s]','')      #removing punct

In [ ]:
#removing url if any
import re
def remove_URL(txt):
    url= re.compile(r"https?://\S+|www\.\S+")
    return url.sub(r"",txt)
t_data['text']=t_data['text'].apply(lambda x:remove_URL(x))

In [ ]:
import numpy as np
from keras.utils.np_utils import to_categorical
from sklearn import preprocessing
labelEncode=preprocessing.LabelEncoder()
labelEncode.fit(t_data['label'])
print (labelEncode.classes_)
train_labelEncode=labelEncode.transform(t_data['label'])
label=to_categorical(np.asarray(train_labelEncode))
label

['Hope_speech' 'Non_hope_speech' 'not-malayalam']


array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [ ]:
#counting labels      
 
t_data['label'].value_counts()
#must use something to balance data

Non_hope_speech    6205
Hope_speech        1668
not-malayalam       691
Name: label, dtype: int64

In [ ]:
#words in each line
 
t_data['totalwords'] = t_data['text'].str.count(' ') + 1
t_data

text  ... totalwords
0                                       arya s nair may be athile karthikayude charctr bisexual ayirikkum  ...         10
1                                            വങങയത എനത കനത ആയല കളയൻ പററലലലല ഇന വങങതരകകൻ ശരദധകകക jai india  ...         11
2     മറമറയകകൻ നടതതയ സമര ഒര previlege issue  ആയരനനഅത ഈ വഷയവമയ കമപയർ ചയയൻ പററലലതങകൾ പറഞഞത തററണസധരണ വഷ അ...  ...         28
3                                                ഇഷന കടതല കടടപടകകണട ഞങങൾകകറയ ഇഷന  സരയയട ഇചചര കഞചൽ കടതലണനന  ...         10
4     ഇനതയ ഇസലമക രജയമലല ഇനതയൻ ഭരണഘടന മതരമ ഇനതയൻ പരനമർ നകകണടതള  ഇനതയൻ നയമ പരകര പരയപർതതയയ രണടപർകക പരസപര ...  ...         22
...                                                                                                   ...  ...        ...
8559                                                              evan eatha eee pottan oru vivaravumilla  ...          6
8560                                               ithinu pakaramayi upayogikkan pattunna indian app undo  ...          7
8561                                                                                        സറന നലലത വരടട  ...          3
8562                                                 ഇങങനതത നലല നലല അറവകൾ പറഞഞ തരനന ഈ ഡകടർക ഇരകകടട ഒര നനദ  ...         11
8563  happy wedding anniverserygod bless you കരയലല അമമ സനതഷതതട  ഇഷനകകയട മനന അമമമരമയ ഈ ജവത ജവചച തർകക എന...  ...         20

[8564 rows x 3 columns]

In [ ]:
import keras
from keras.preprocessing.text import Tokenizer
tok1 = Tokenizer(char_level=False, filters ='!"$%&@()*+,-./:;”“<=>?[\\]^_`{|}~\t\n', lower = True)

In [ ]:
tok2=Tokenizer(char_level=True,filters ='!"$%&@()*+,-./:;”“<=>?[\\]^_`{|}~\t\n',lower=True)

In [ ]:
tok1.fit_on_texts(t_data['text'])
words=len(tok1.word_counts)
words

28996

In [ ]:
tok2.fit_on_texts(t_data['text'])
ltr=len(tok2.word_counts)
ltr

124

In [ ]:
Charlist=tok2.word_index
#Charlist

In [ ]:
wordlist=tok1.word_index
#wordlist

In [ ]:
encode=tok1.texts_to_sequences(t_data['text'])
print(t_data['text'][5555])
encode[5555]

dr ന പല തവണ വളചച പരജയ പടട ഒര വകത ആണ


[39, 24, 11, 1306, 528, 2623, 854, 1, 917, 2]

In [ ]:
##         Padding encoded sequence of words
from keras.preprocessing import sequence
max_length=40
padd = sequence.pad_sequences(encode, maxlen=max_length, padding='post')
padd

array([[ 3584,   227,  1049, ...,     0,     0,     0],
       [ 8672,    18,  2252, ...,     0,     0,     0],
       [ 8674,  2798,  2254, ...,     0,     0,     0],
       ...,
       [ 4712,   180,  1137, ...,     0,     0,     0],
       [ 5506,    31,    31, ...,     0,     0,     0],
       [   28,    68, 28994, ...,     0,     0,     0]], dtype=int32)

In [ ]:
cencode=tok2.texts_to_sequences(t_data['text'])
cpadd=sequence.pad_sequences(cencode,70,padding='post')

In [ ]:
# importing libraries for creating model
import tensorflow as tf
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Embedding,MaxPool1D,Input
from tensorflow.keras.layers import Conv1D, GlobalMaxPooling1D, MaxPooling1D,LSTM,Bidirectional,GlobalAveragePooling1D
from keras.layers.merge import concatenate

#w2v Embedding

In [ ]:
embeddings_index = {}
f = open('/content/drive/MyDrive/Ankit/dec 2020 codalab/Hope speech/malyalam/Mal w2v.txt')
for line in f:
    values = line.split()
    word = values[0]
    coefs = np.asarray(values[1:])
    embeddings_index[word] = coefs
f.close()
print('Loaded %s word vectors.' % len(embeddings_index))

Loaded 36657 word vectors.


In [ ]:
embedding_matrix = np.zeros((words+1, 300))
for word, i in tok1.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector

#Embedding layer

In [ ]:
Embedding_Layer = Embedding(words+1,300,weights=[embedding_matrix], input_length=max_length, trainable=False)
Embedding_Layer2=Embedding(words+1,300,input_length=max_length)
Embedding_Layer3=Embedding(ltr+1,300,input_length=70)

#MODEL

In [ ]:
# channel 1
inputs1 = Input(shape=(max_length,))
embedding1 = Embedding_Layer(inputs1)
conv1 = Bidirectional(LSTM(128))(embedding1)
drop1 = Dropout(0.5)(conv1)
#pool1 = MaxPooling1D(pool_size=2)(drop1)
#conv12=Conv1D(filters=64,kernel_size=4,activation='relu')(pool1)
#drop12=Dropout(0.5)(conv12)
#pool12=MaxPooling1D(pool_size=3,padding='same')(drop12)
flat1 =(drop1)

In [ ]:
# channel 2
inputs2 = Input(shape=(max_length,))
embedding2 =Embedding_Layer(inputs2)
conv2 = Bidirectional(LSTM(128))(embedding2)
drop2 = Dropout(0.5)(conv2)
#pool2 = MaxPooling1D(pool_size=2)(drop2)
flat2 =(drop2)

In [ ]:
#channel 3
inputs3=Input(shape=(70,))
embedding3=Embedding_Layer3(inputs3)
conv3=Bidirectional(LSTM(64))(embedding3)
drop3=Dropout(0.5)(conv3)
flat3=(drop3)

In [ ]:
merged = concatenate([flat3, flat2,flat1])
dense1 = Dense(256, activation='relu')(merged)
dense2=Dense(128,activation='relu')(dense1)
outputs = Dense(3, activation='sigmoid')(dense2)
model = Model(inputs=[inputs3, inputs2,inputs1], outputs=outputs)
model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_4 (InputLayer)            [(None, 70)]         0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 40)]         0                                            
__________________________________________________________________________________________________
input_1 (InputLayer)            [(None, 40)]         0                                            
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, 70, 300)      37500       input_4[0][0]                    
____________________________________________________________________________________________

#compile

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])


#Training models

In [ ]:
model.fit([cpadd,padd,padd],label,epochs=50,verbose=1,batch_size=128)

Epoch 1/50
67/67 [==============================] - 74s 971ms/step - loss: 0.3272 - acc: 0.7729
Epoch 2/50
67/67 [==============================] - 63s 939ms/step - loss: 0.1054 - acc: 0.9338
Epoch 3/50
67/67 [==============================] - 64s 953ms/step - loss: 0.0987 - acc: 0.9371
Epoch 4/50
67/67 [==============================] - 63s 944ms/step - loss: 0.0962 - acc: 0.9385
Epoch 5/50
67/67 [==============================] - 65s 970ms/step - loss: 0.0910 - acc: 0.9419
Epoch 6/50
67/67 [==============================] - 67s 1s/step - loss: 0.0814 - acc: 0.9485
Epoch 7/50
67/67 [==============================] - 66s 986ms/step - loss: 0.0817 - acc: 0.9526
Epoch 8/50
67/67 [==============================] - 65s 973ms/step - loss: 0.0821 - acc: 0.9472
Epoch 9/50
67/67 [==============================] - 65s 967ms/step - loss: 0.0777 - acc: 0.9501
Epoch 10/50
67/67 [==============================] - 66s 991ms/step - loss: 0.0755 - acc: 0.9519
Epoch 11/50
67/67 [=======================

#Development data

In [3]:
d_data=pd.read_csv('/content/drive/MyDrive/Ankit/EACL 2021 dec 2020/Hope speech/malyalam/malayalam_hope_dev.csv',names=['text','label','nan'],sep='\t')

In [4]:
d_data=d_data[["text","label"]]
d_data

text            label
0     ജനകീയ കോടതിയുടെ വളരെ മികച്ച എപിസോടുകളിൽ ഒന്ന്... നല്ല കലക്കൻ സംവാദം... കിടു ചർച്ച... nനിലപാടുകൾn...      Hope_speech
1                                                                      Opera Mini - യുടെ അത്രേം വരില്ല UC  Non_hope_speech
2     മറ്റുള്ള hetero sexuals നെ പോലെ കഴിവും സംസ്ക്കാരവുമൊക്കെയുള്ള വിഭാഗമാണവരും. അവരുടെ കുറവുകൾ മനസ്സ...      Hope_speech
3                                                                @Mr President നിനക്ക് ഓക്കെ അത നല്ലത്...  Non_hope_speech
4     RSS തീവ്രവാദികൾ നേരത്തെ പദ്ധതി ഇട്ട പ്രകാരം ചൈനയുമായി ചേർന്ന് നടത്തുന്ന ഒരു നാടകമാണിത്. ബലിയാടാവ...  Non_hope_speech
...                                                                                                   ...              ...
1065                                                 വാട്സ്ആപ്പ് ന് പകരം telegram app ഇത് ഇന്ത്യ യുടെ ആണ്  Non_hope_speech
1066                                    അടിസ്ഥാനമായി പള്ളിപ്രമാണങ്ങൾ മാറ്റിയെഴുതേണ്ടി വരും. nnഅരുൺ പൊളിയെ  Non_hope_speech
1067                                          Vella samsarikumpo blu ne nok..chevi kelkaatha pennine pole  Non_hope_speech
1068                                    നികേഷിന്റെ വോളിൽ അമമയുടെ കൂടെ രണ്ടു പേരും നിൽക്കുന്ന ഫോട്ടോ ഉണ്ട്  Non_hope_speech
1069                                                                 Mx player  അടിപൊളിയായിട് ഷെയർ cheyam  Non_hope_speech

[1070 rows x 2 columns]

In [5]:
d_data['label'].value_counts()

Non_hope_speech    784
Hope_speech        190
not-malayalam       96
Name: label, dtype: int64

In [ ]:
#processing as training set

d_data['text']=d_data['text'].str.lower()       #changing into lower case       (remove and check acc too)
d_data['text']=d_data['text'].str.strip()       #remove white spaces
d_data['text']=d_data['text'].str.replace(r'\d+','')   #remove numbers
#d_data['text']=d_data['text'].apply(lambda x: x.encode('ascii', 'ignore').decode('ascii'))  #removing emoji
d_data['text']=d_data['text'].str.replace('[^\w\s]','')      #removing punct
d_data['text']=d_data['text'].apply(lambda x:remove_URL(x))
#d_data['text'] = d_data['text'].apply(lambda x: remove_sw(x))


In [ ]:
encoded1 =tok1.texts_to_sequences(d_data['text'])
print(d_data['text'][0])
encoded1[0]

ജനകയ കടതയട വളര മകചച എപസടകളൽ ഒനന നലല കലകകൻ സവദ കട ചർചച nനലപടകൾnപതയ കഴചപപടകൾ ndr arun


[1267, 65, 1612, 14, 31, 21995, 40, 977, 18818, 110]

In [ ]:
padded = sequence.pad_sequences(encoded1, maxlen=max_length, padding='post')
padded[0]

array([ 1267,    65,  1612,    14,    31, 21995,    40,   977, 18818,
         110,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0], dtype=int32)

In [ ]:
cencoded1=tok2.texts_to_sequences(d_data['text'])
cpadded=sequence.pad_sequences(cencoded1,70,padding='post')

In [ ]:
val_labelEncode=labelEncode.transform(d_data['label'])
val_label=to_categorical(np.asarray(val_labelEncode))
val_label[0]

array([1., 0., 0.], dtype=float32)

#prediction

In [ ]:

# devlopment prediction of CNN

dev_predictions = model.predict([cpadded,padded,padded])
# Finding out of two output neurons which one has highest probability
# It will return us the predicted class
# It will convert probability into final class 1 and 0
dev_predictions1 = np.zeros_like(dev_predictions)
dev_predictions1[np.arange(len(dev_predictions)), dev_predictions.argmax(1)] = 1
#print(dev_predictions)
#print(dev_predictions1)

#Acuracy report

In [ ]:
#Accuracy CNN
from sklearn.metrics import classification_report
print(classification_report(val_label,dev_predictions1))

              precision    recall  f1-score   support

           0       0.49      0.47      0.48       190
           1       0.86      0.85      0.86       784
           2       0.68      0.74      0.71        96

   micro avg       0.78      0.78      0.78      1070
   macro avg       0.68      0.69      0.68      1070
weighted avg       0.78      0.78      0.78      1070
 samples avg       0.78      0.78      0.78      1070



#TESTING

In [ ]:
tx_data=pd.read_csv('/content/drive/MyDrive/Ankit/dec 2020 codalab/Hope speech/malyalam/malayalam_hope_test.csv',names=['text'],sep=',')
tx_data


text
0                                                                                 അതെ അണപൊട്ടി ഒഴുകുകയാണ്
1                                                                                 കെവിൻ avde pettupoyi🤣🤣🤣
2                       @my voice ullup illa daaa tayoli ath kond alle ninte ammaye njan panniyatha monee
3                                                                                            @Albin Baiju
4                                                                                         I respect you..
...                                                                                                   ...
1066  ചേട്ടാ അതിന് ഇവിടെ ആരാണ് ഇന്ത്യൻ മൊബൈൽ റിവ്യൂ ചെയ്യുന്നത്  ചില ഉത്തരേന്ത്യൻ ചാനൽ ചെയ്യും  ഇവിടെ ...
1067                                                                                        @surya ishaan
1068                                                                  ഏതാണ് ആ മൂലയിൽ ഇരിക്കുന്ന അപ്പൂപ്പൻ
1069                                                     ഏതാ ആ ചൊമന്ന ടി ഷർട്ടിന് മേൽ കോട്ടിട്ട വവ്വാൽ...
1070                                                                                Poorru  angodu chellu

[1071 rows x 1 columns]

In [ ]:
#PREprocessing
#processing as training set

tx_data['text']=tx_data['text'].str.lower()       #changing into lower case       (remove and check acc too)
tx_data['text']=tx_data['text'].str.strip()       #remove white spaces
tx_data['text']=tx_data['text'].str.replace(r'\d+','')   #remove numbers
#t_data['text']=t_data['text'].apply(lambda x: x.encode('ascii', 'ignore').decode('ascii'))  #removing emoji
tx_data['text']=tx_data['text'].str.replace('[^\w\s]','')      #removing punct
tx_data['text']=tx_data['text'].apply(lambda x:remove_URL(x))
#t_data['text'] = t_data['text'].apply(lambda x: remove_sw(x))


In [ ]:
encoded2 =tok1.texts_to_sequences(tx_data['text'])
padded2 = sequence.pad_sequences(encoded2, maxlen=max_length, padding='post')

In [ ]:
cencoded2=tok2.texts_to_sequences(tx_data['text'])
cpadded2=sequence.pad_sequences(cencoded2,maxlen=70,padding='post')

In [ ]:
#prediction
#prediction of CNN

predictions = model.predict([cpadded2,padded2,padded2])
# Finding out of two output neurons which one has highest probability
# It will return us the predicted class
# It will convert probability into final class 1 and 0
predictions1 = np.zeros_like(predictions)
predictions1[np.arange(len(predictions)), predictions.argmax(1)] = 1
#print(dev_predictions)
print(predictions1)

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
test_predictions12=np.argmax(predictions1,axis=1)
tx_data['label']=labelEncode.inverse_transform(test_predictions12)
tx_data

text            label
0                                                                                         അത അണപടട ഒഴകകയണ  Non_hope_speech
1                                                                                      കവൻ avde pettupoyi  Non_hope_speech
2                        my voice ullup illa daaa tayoli ath kond alle ninte ammaye njan panniyatha monee  Non_hope_speech
3                                                                                             albin baiju    not-malayalam
4                                                                                           i respect you    not-malayalam
...                                                                                                   ...              ...
1066  ചടട അതന ഇവട ആരണ ഇനതയൻ മബൽ റവയ ചയയനനത  ചല ഉതതരനതയൻ ചനൽ ചയയ  ഇവട പറയനനണട അവർ ചനസ മബൽ വങങചച റവയ ചയയ...      Hope_speech
1067                                                                                         surya ishaan    not-malayalam
1068                                                                             ഏതണ ആ മലയൽ ഇരകകനന അപപപപൻ  Non_hope_speech
1069                                                                      ഏത ആ ചമനന ട ഷർടടന മൽ കടടടട വവവൽ  Non_hope_speech
1070                                                                                poorru  angodu chellu    not-malayalam

[1071 rows x 2 columns]

In [ ]:
test=pd.read_csv('/content/drive/MyDrive/Ankit/dec 2020 codalab/Hope speech/malyalam/malayalam_hope_test.csv',names=['text'],sep=',')
test['label']=labelEncode.inverse_transform(test_predictions12)
test

text            label
0                                                                                 അതെ അണപൊട്ടി ഒഴുകുകയാണ്  Non_hope_speech
1                                                                                 കെവിൻ avde pettupoyi🤣🤣🤣  Non_hope_speech
2                       @my voice ullup illa daaa tayoli ath kond alle ninte ammaye njan panniyatha monee  Non_hope_speech
3                                                                                            @Albin Baiju    not-malayalam
4                                                                                         I respect you..    not-malayalam
...                                                                                                   ...              ...
1066  ചേട്ടാ അതിന് ഇവിടെ ആരാണ് ഇന്ത്യൻ മൊബൈൽ റിവ്യൂ ചെയ്യുന്നത്  ചില ഉത്തരേന്ത്യൻ ചാനൽ ചെയ്യും  ഇവിടെ ...      Hope_speech
1067                                                                                        @surya ishaan    not-malayalam
1068                                                                  ഏതാണ് ആ മൂലയിൽ ഇരിക്കുന്ന അപ്പൂപ്പൻ  Non_hope_speech
1069                                                     ഏതാ ആ ചൊമന്ന ടി ഷർട്ടിന് മേൽ കോട്ടിട്ട വവ്വാൽ...  Non_hope_speech
1070                                                                                Poorru  angodu chellu    not-malayalam

[1071 rows x 2 columns]

#into tsv

In [ ]:
test.to_csv('iiit_dwd_Malayalam.tsv',index=False)